version: '3.7'

services:
  app:
    image: c-blog
    build: .
    ports:
      - 3000:80
    volumes:
      - type: bind
      - .:/app
      - /app/node_modules
    restart: unless-stopped
    environment:
      - CHOKIDAR_USEPOLLING=true
