version: '3.7'

services:
  app:
    image: c-blog
    build: .
    ports:
      - 3000:80
    volumes:
      - type: bind
        source: .
        target: /app
    restart: unless-stopped
    environment:
      - CHOKIDAR_USEPOLLING=true
